"""add soft delete column

Revision ID: 3317682fcf55
Revises: 5aacd3cb0353
Create Date: 2025-04-07 22:08:05.858041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3317682fcf55'
down_revision: Union[str, None] = '5aacd3cb0353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('bank_transactions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('subcategories', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcategories', 'deleted_at')
    op.drop_column('categories', 'deleted_at')
    op.drop_column('bank_transactions', 'deleted_at')
    op.drop_column('bank_accounts', 'deleted_at')
    # ### end Alembic commands ###
