"""refactor: add unique constraint on user_id and created_at

Revision ID: 6e6cc13681f8
Revises: cb440bc32b9f
Create Date: 2025-04-08 20:29:32.784404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6cc13681f8'
down_revision: Union[str, None] = 'cb440bc32b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_created_at', 'bank_transactions', ['user_id', 'created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_created_at', 'bank_transactions', type_='unique')
    # ### end Alembic commands ###
