"""refactor: use date column instead of created_at to be aplicaple for laravel

Revision ID: ca4d60c11441
Revises: 5887fcc09637
Create Date: 2025-04-08 22:32:49.279644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca4d60c11441'
down_revision: Union[str, None] = '5887fcc09637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_date', 'bank_transactions', ['user_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_date', 'bank_transactions', type_='unique')
    # ### end Alembic commands ###
