"""refactor: add created_at column in bank transaction

Revision ID: cb440bc32b9f
Revises: 5887fcc09637
Create Date: 2025-04-08 20:23:32.587163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb440bc32b9f'
down_revision: Union[str, None] = '5887fcc09637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_transactions', 'created_at')
    # ### end Alembic commands ###
